#!/bin/bash

set -e
adduser --system --no-create-home --group whackd
chown whackd:whackd /var/lib/whackd

dialog_user() {
  exec 3>&1

  WEB3_HELP="To monitor the Ethereum Network for WHACKD Transactions, you need a Web3 Provider such as infura.io or your own Eth1 node (ex.: Go-Ethereum, OpenEthereum, Trinity, Nimbus).
Please provide an URL for a Web3 Provider.
  
ex.: https://mainnet.infura.io/v3/xxx"

  WEB3_URL=$(dialog --title "Eth1 Web3 Provider" \
    --clear \
    --inputbox "${WEB3_HELP}" 20 110 2>&1 1>&3)

  # check for empty Web3 Provider
  if [ -z $WEB3_URL ]; then
    echo "You didn't provide any Eth1 Web3 Provider.
You should fix this by editing /usr/lib/systemd/system/whackd.service and setting proper value on WEB3_URL."
  fi

  # check for Web3 Provider URL prefixes (https:// or wss://)
  if [[ !( -z $WEB3_URL ) && !( $WEB3_URL =~ ^https\:\/\/.* || $WEB3_URL =~ ^wss\:\/\/.* ) ]]; then
    echo "You provided an invalid Eth1 Web3 Provider. You should fix this by editing /usr/lib/systemd/system/whackd.service and setting proper value on WEB3_URL"
  fi

  echo "Environment=WEB3_URL=${WEB3_URL}" >>/usr/lib/systemd/system/whackd.service
}

while true; do
  read -p "Do you want to be assisted in the configuration of the WHACKD SystemD Service? y/n " yn
  case $yn in
  [Yy]*)
    dialog_user
    break
    ;;
  [Nn]*)
    echo "Warning: you must manually edit /usr/lib/systemd/system/whackd.service and setting proper values on WEB3_URL."
    echo "Environment=WEB3_URL=" >>/usr/lib/systemd/system/whackd.service
    exit
    ;;
  *) echo "Please answer yes or no." ;;
  esac
done

